// Generated by CoffeeScript 1.6.1

/*
generateTags.js
A JavaScript function that processes plain text or HTML (1st argument, as string)
and produces a keyword frequency hash to facilitate tagging.
Optional second argument: options object, governs the behaviour and output format.
Can produce output suitable for the Wordle.net word cloud generator.

This is free software (free as in free beer), published under the MIT license,
see http://opensource.org/licenses/MIT

This file is generated from its coffeescript source, see generateTags.coffee.md
*/


(function() {
  var defaults, htmlDecode, html_tags, stopwords;

  defaults = {
    limit: 0,
    blacklist: "",
    ignoreStopwords: true,
    minLength: 0,
    minFrequency: 0,
    ignoreCase: true,
    retainProperNames: true,
    ignorePunctuation: true,
    ignoreNonTextTags: true,
    outputFormat: 'list'
  };

  stopwords = "a about above after again against all am an and any are aren't as at be because been before being below between both but by can't cannot could couldn't did didn't do does doesn't doing don't down during each few for from further had hadn't has hasn't have haven't having he he'd he'll he's her here here's hers herself him himself his how how's i i'd i'll i'm i've if in into is isn't it it's its itself let's me more most mustn't my myself no nor not of off on once only or other ought our ours  ourselves out over own same shan't she she'd she'll she's should shouldn't so some such than that that's the their theirs them themselves then there there's these they they'd they'll they're they've this those through to too under until up very was wasn't we we'd we'll we're we've were weren't what what's when when's where where's which while who who's whom why why's with won't would wouldn't you you'd you'll you're you've your yours yourself yourselves";

  html_tags = "button head script map style audio video canvas svg data";

  htmlDecode = function(input) {
    var e;
    if (typeof document === "undefined" || document === null) {
      return input;
    }
    (e = document.createElement('div')).innerHTML = input;
    return e.firstChild.nodeValue;
  };

  /*
  @param html: a string containing the HTML to be processed
  @param options: the options object, as follows (default values)
    limit: 0                   # maximum number of most frequent words (0: no limit)
    blacklist: ""              # comma- or space separated strings to ignore (e.g. swear words)
                               # in addition to stopwords
    ignoreStopwords: true      # see list of English stopwords below
    minLength: 0               # ignore shorter words (0: no minimum length)
    minFrequency: 0            # ignore words below a frequency threshold (0: no limit)
    ignoreCase: true           # by default, treat "House" and "house" as the same word
    retainProperNames: true    # don't ignore case when you see "Chuck Norris"
    ignorePunctuation: true    # only set this to false if it ¿really? matters to you
    ignoreNonTextTags: true    # ignore <script>, <style>, <img>, <video>, <audio> and friends
    outputFormat: 'list'       # Array, sorted by frequency descending
  */


  this.generateTags = function(html, options) {
    var opts, re, x;
    opts = options || {};
    for (x in defaults) {
      opts[x] = opts[x] === void 0 ? defaults[x] : opts[x];
    }
    if (opts[ignoreNonTextTags]) {
      re = new RegExp("<(" + (html_tags.replace(/\s/g, '|')) + ").+?</\\1>", "gi");
      html = html.replace(re, " ");
    }
    html = html.replace(/<.+?>/g, " ");
    html = htmlDecode(html);
    return html = html.replace(/[]/);
  };

}).call(this);
